config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root 'joboffers#index'
  resources :joboffers
  resources :communes
  resources :cities
  resources :regions
  resources :skills
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/commune.rb
class Commune < ApplicationRecord
	has_many :joboffers
	has_many :users
end

app/controllers/communes_controller.rb
class CommunesController < ApplicationController
  before_action :set_commune, only: [:show, :edit, :update, :destroy]

  # GET /communes
  # GET /communes.json
  def index
    @communes = Commune.all
  end

  # GET /communes/1
  # GET /communes/1.json
  def show
  end

  # GET /communes/new
  def new
    @commune = Commune.new
  end

  # GET /communes/1/edit
  def edit
  end

  # POST /communes
  # POST /communes.json
  def create
    @commune = Commune.new(commune_params)

    respond_to do |format|
      if @commune.save
        format.html { redirect_to @commune, notice: 'Commune was successfully created.' }
        format.json { render :show, status: :created, location: @commune }
      else
        format.html { render :new }
        format.json { render json: @commune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communes/1
  # PATCH/PUT /communes/1.json
  def update
    respond_to do |format|
      if @commune.update(commune_params)
        format.html { redirect_to @commune, notice: 'Commune was successfully updated.' }
        format.json { render :show, status: :ok, location: @commune }
      else
        format.html { render :edit }
        format.json { render json: @commune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communes/1
  # DELETE /communes/1.json
  def destroy
    @commune.destroy
    respond_to do |format|
      format.html { redirect_to communes_url, notice: 'Commune was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commune
      @commune = Commune.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commune_params
      params.require(:commune).permit(:name, :display_in_index)
    end
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/views/communes/_form.html.erb
<%= simple_form_for(@commune) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :display_in_index %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/communes/edit.html.erb
<h1>Editing Commune</h1>

<%= render 'form', commune: @commune %>

<%= link_to 'Show', @commune %> |
<%= link_to 'Back', communes_path %>

app/views/communes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Communes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Display in index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @communes.each do |commune| %>
      <tr>
        <td><%= commune.name %></td>
        <td><%= commune.display_in_index %></td>
        <td><%= link_to 'Show', commune %></td>
        <td><%= link_to 'Edit', edit_commune_path(commune) %></td>
        <td><%= link_to 'Destroy', commune, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commune', new_commune_path %>

app/views/communes/new.html.erb
<h1>New Commune</h1>

<%= render 'form', commune: @commune %>

<%= link_to 'Back', communes_path %>

app/views/communes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @commune.name %>
</p>

<p>
  <strong>Display in index:</strong>
  <%= @commune.display_in_index %>
</p>

<%= link_to 'Edit', edit_commune_path(@commune) %> |
<%= link_to 'Back', communes_path %>