config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  root 'joboffers#index'
  resources :joboffers
  resources :communes
  resources :cities
  resources :regions
  resources :skills
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/joboffer.rb
class Joboffer < ApplicationRecord
  belongs_to :region
  belongs_to :commune
  belongs_to :city
  belongs_to :user
  belongs_to :skill
  has_one_attached :image1
end

app/controllers/joboffers_controller.rb
class JoboffersController < ApplicationController
  before_action :set_joboffer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show,:edit, :update, :new, :create]
  # GET /joboffers
  # GET /joboffers.json
  def index
    @joboffers = Joboffer.all
  end

  # GET /joboffers/1
  # GET /joboffers/1.json
  def show
  end

  # GET /joboffers/new
  def new
    @joboffer = current_user.joboffers.build
  end

  # GET /joboffers/1/edit
  def edit
  end

  # POST /joboffers
  # POST /joboffers.json
  def create
    @joboffer = current_user.joboffers.build(joboffer_params)
    respond_to do |format|
      if @joboffer.save
        format.html { redirect_to @joboffer, notice: 'Joboffer was successfully created.' }
        format.json { render :show, status: :created, location: @joboffer }
      else
        format.html { render :new }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joboffers/1
  # PATCH/PUT /joboffers/1.json
  def update
    respond_to do |format|
      if @joboffer.update(joboffer_params)
        format.html { redirect_to @joboffer, notice: 'Joboffer was successfully updated.' }
        format.json { render :show, status: :ok, location: @joboffer }
      else
        format.html { render :edit }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joboffers/1
  # DELETE /joboffers/1.json
  def destroy
    @joboffer.destroy
    respond_to do |format|
      format.html { redirect_to joboffers_url, notice: 'Joboffer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joboffer
      @joboffer = Joboffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joboffer_params
      params.require(:joboffer).permit(:title, :description, :image, :budget, :region_id, :commune_id, :city_id, :user_id, :skill_id, :image1)
    end
end

app/helpers/joboffers_helper.rb
module JoboffersHelper
end

app/views/joboffers/_form.html.erb
<%= simple_form_for(@joboffer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :image1 %>
    <%= f.input :budget %>

    <%= f.association :region %>
    <%= f.association :commune %>
    <%= f.association :city %>
    <%= f.association :user %>
    <%= f.association :skill %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/joboffers/edit.html.erb
<h1>Editing Joboffer</h1>

<%= render 'form', joboffer: @joboffer %>

<%= link_to 'Show', @joboffer %> |
<%= link_to 'Back', joboffers_path %>

app/views/joboffers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Joboffers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th>Budget</th>
      <th>Region</th>
      <th>Commune</th>
      <th>City</th>
      <th>User</th>
      <th>Skill</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @joboffers.each do |joboffer| %>
      <tr>
        <td><%= joboffer.title %></td>
        <td><%= joboffer.description %></td>
        <td> <%= image_tag(joboffer.image1) if joboffer.image1.attached? %></td>

        <td><%= joboffer.budget %></td>
        <td><%= joboffer.region.name %></td>
        <td><%= joboffer.commune.name %></td>
        <td><%= joboffer.city.name %></td>
        <td><%= joboffer.user.name %></td>
        <td><%= joboffer.skill.name %></td>
        <td><%= link_to 'Show', joboffer %></td>
        <td><%= link_to 'Edit', edit_joboffer_path(joboffer) %></td>
        <td><%= link_to 'Destroy', joboffer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Joboffer', new_joboffer_path %>

app/views/joboffers/new.html.erb
<h1>New Joboffer</h1>

<%= render 'form', joboffer: @joboffer %>

<%= link_to 'Back', joboffers_path %>

app/views/joboffers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @joboffer.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @joboffer.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @joboffer.image1 %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @joboffer.budget %>
</p>

<p>
  <strong>Region:</strong>
  <%= @joboffer.region %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @joboffer.commune %>
</p>

<p>
  <strong>City:</strong>
  <%= @joboffer.city %>
</p>

<p>
  <strong>User:</strong>
  <%= @joboffer.user %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @joboffer.skill %>
</p>

<%= link_to 'Edit', edit_joboffer_path(@joboffer) %> |
<%= link_to 'Back', joboffers_path %>